In [10]:
import json
import requests

In [1]:
import pandas as pd

In [3]:
URI = "https://www.imf.org/external/datamapper/api/v1/indicators"

In [4]:
data = requests.get(URI).json()

In [5]:
data["indicators"].keys()

dict_keys(['NGDP_RPCH', 'NGDPD', 'NGDPDPC', 'PPPGDP', 'PPPPC', 'PPPSH', 'PPPEX', 'PCPIPCH', 'PCPIEPCH', 'LP', 'BCA', 'BCA_NGDPD', '', 'LUR', 'GGXCNL_NGDP', 'GGXWDG_NGDP', 'rev', 'exp', 'prim_exp', 'ie', 'pb', 'd', 'rgc', 'rltir', 'extensive', 'intensive', 'total_theil', 'SITC1_0', 'SITC1_1', 'SITC1_2', 'SITC1_3', 'SITC1_4', 'SITC1_5', 'SITC1_6', 'SITC1_7', 'SITC1_8', 'SITC1_9', 'SITC1_total', 'DirectAbroad', 'DirectIn', 'PrivInexDI', 'PrivInexDIGDP', 'PrivOutexDI', 'PrivOutexDIGDP', 'Portfa', 'Portfl', 'EquityA', 'EquityL', 'DebtA', 'DebtL', 'OtherGov', 'OtherA', 'OtherL', 'Deriv', 'DebtForg', 'GDP', 'ka_new', 'ka_in', 'ka_out', 'FM_ka', 'Nonres_ka', 'Res_ka', 'Ka_eq', 'Ka_bo', 'Ka_mm', 'Ka_ci', 'Ka_dr', 'Ka_cc', 'Ka_fc', 'Ka_gu', 'Ka_di', 'ka_ldi', 'ka_ret', 'ka_pct', 'Reserves_ARA', 'Reserves_M2', 'Reserves_STD', 'Reserves_M', 'GRB_dummy', 'GDI_TC', 'GII_TC', 'DEBT1', 'Privatedebt_all', 'HH_ALL', 'NFC_ALL', 'PVD_LS', 'HH_LS', 'NFC_LS', 'PS_DEBT_GDP', 'NFPS_DEBT_GDP', 'GG_DEBT_GDP', 'CG_DEBT_GDP', 'GGXCNL_G01_GDP_PT', 'GGXONLB_G01_GDP_PT', 'GGCB_G01_PGDP_PT', 'GGCBP_G01_PGDP_PT', 'GGR_G01_GDP_PT', 'G_X_G01_GDP_PT', 'G_XWDG_G01_GDP_PT', 'GGXWDN_G01_GDP_PT', 'NGDP_R_PCH', 'NGDPXO_RPCH', 'NGDPRPC_PCH', 'NI_GDP', 'NGS_GDP', 'GGXCNL_GDP', 'GGXCNLXG_GDP', 'GGRXG_GDP', 'GGX_GDP', 'GGXWDG_GDP', 'FMB_GDP', 'FDSAOP_PCH', 'FDSAOP_GDP', 'FMB_PCH', 'BX_GDP', 'BCA_GDP', 'BM_GDP', 'BT_GDP', 'BFD_GDP', 'BRASS_MI', 'EREER', 'ENEER', 'DG_GDP', 'PCPI_PCH', 'PCPIE_PCH', 'TTT', 'FR_ind', 'FC_dummy'])

In [11]:
data["indicators"]["NGDP_RPCH"]

{'label': 'Real GDP growth',
 'description': "Gross domestic product is the most commonly used single measure of a country's overall economic activity. It represents the total value at constant prices of final goods and services produced within a country during a specified time period, such as one year.",
 'source': 'World Economic Outlook (October 2023)',
 'unit': 'Annual percent change',
 'dataset': 'WEO'}

In [ ]:
"https://api.worldbank.org/v2/en/country/IND?downloadformat=excel"

In [6]:
pd.DataFrame(data["indicators"]).T.to_excel("indicators.xlsx")

In [3]:
frame = pd.DataFrame({1980 : {"WDI.ICP.GDP" : {"IMF" : 10, "WB" : 10}, "WDI.ICP.GDPD" : {"IMF" : 20, "WB" : 20}}, 1981 : {"WDI.ICP.GDP" : {"IMF" : 30, "WB" : 30}, "WDI.ICP.GDPD" : {"IMF" : 40, "WB" : 40}}})
frame

                               1980                   1981
WDI.ICP.GDP   {'IMF': 10, 'WB': 10}  {'IMF': 30, 'WB': 30}
WDI.ICP.GDPD  {'IMF': 20, 'WB': 20}  {'IMF': 40, 'WB': 40}

In [ ]:
class MacroIndicator:

In [ ]:
INDICATOR = "WDI.ICP.GDP"

In [13]:
pd.DataFrame({1980 : {"WDI.ICP.GDP" : 10, "WDI.ICP.GDPD" : 20}, 1981 : {"WDI.ICP.GDP" : 30, "WDI.ICP.GDPD" : 40}})

              1980  1981
WDI.ICP.GDP     10    30
WDI.ICP.GDPD    20    40

In [4]:
import os

In [5]:
from connections import connect

In [8]:
con, cur, engine, server = connect(
    username = os.getenv("MSSQL_DEV_USERNAME"),
    password = os.getenv("MSSQL_DEV_PASSWORD"),
    server = os.getenv("MSSQL_DEV_SERVER"),
    database = "pidprdevsa",
    engine = True,
    fast_executemany = True
)

In [20]:
frame = pd.DataFrame(data = {
    "YR" : [1983, 1984, 1985],
    "VL" : [{'IMF' : 40, 'WB' : 10.1}, {'IMF' : 50, 'WB' : 80.1}, {'IMF' : 60, 'WB' : 70.1}]
})
frame

     YR                       VL
0  1983  {'IMF': 40, 'WB': 10.1}
1  1984  {'IMF': 50, 'WB': 80.1}
2  1985  {'IMF': 60, 'WB': 70.1}

In [21]:
frame["VL"] = frame["VL"].apply(lambda x : json.dumps(x, default = str))

In [22]:
frame

     YR                       VL
0  1983  {"IMF": 40, "WB": 10.1}
1  1984  {"IMF": 50, "WB": 80.1}
2  1985  {"IMF": 60, "WB": 70.1}

In [23]:
frame.to_sql("tmpGlobalIndicator", engine, schema = "dbo", if_exists = "append", index = False)

-1

In [8]:
pd.read_excel("indicators.xlsx", sheet_name = "Sheet1", nrows = 3).set_index("IndicatorID").to_sql("mwGlobalIndicators", engine, schema = "dbo", if_exists = "append")

-1

In [24]:
con.close()
server.close()